CIRgetR
=======

R interface for chemical identifier translation through the [Chemical Identifier Resolver (CIR)](http://cactus.nci.nih.gov/chemical/structure) by the CADD Group at the NCI/NIH.

Install package.
```{r,message=FALSE, warning=FALSE, results='hide'}
install.packages("devtools");install.packages("RJSONIO")
library(devtools);library(RJSONIO)

install_github(repo = "CIRgetR", username = "dgrapov")
library(CIRgetR)
```

Try translating inchi codes.
```{r,message=FALSE, warning=FALSE}
#test
id<-"CYQFCXCEBYINGO-IAGOWNOFSA-N"
opts<-c("smiles", "names", "iupac_name", "cas", "inchi", "stdinchi", "inchikey", "stdinchikey",
		"ficts", "ficus", "uuuuu", "image", "file", "mw", "monoisotopic_mass","chemspider_id",
		"pubchem_sid", "chemnavigator_sid", "formula", "chemnavigator_sid")		
		
translations<-lapply(1:length(opts), function(i)
	{
		CIRgetR(id=id,to=opts[i],return.all=FALSE, progress=FALSE)
	})
translations<-do.call("cbind",translations)
t(translations)
# colnames(translations)<-opts
# translations
```

Show structures.
```{r fig.width=10, fig.height=9,message=FALSE, warning=FALSE}
install.packages("caTools")
library(caTools)
image.url<-as.character(translations$image[1])
gif <- read.gif(image.url, verbose = TRUE, flip = TRUE)
par(pin=c(3,3))
image(gif$image, col = gif$col, main =as.character(translations$name[1]), frame.plot=FALSE,xaxt="n", yaxt="n") 

```
